w , writelines ,
 r , read the file ,
  a , it append the data and it can auto create file which you name if it dosent exist, 
wb , open the file for writing in binary mode  if the file exist all the contents in it will be erased and it create a new file if it didnt exist commonly used for images and audio files, 
there is something 
.bin file
.writelines , writes multiples strings in sequence like a=['what /n','man /n'] this will be printed one line after another

In [11]:
with open('example.txt','r')as file:
          content=file.read()
          print(content)

hellow world
append iteration taking place!
append iteration taking place!

In [12]:
with open('example.txt','a')as file:
           file.write("append iteration taking place! \n")

In [13]:
lines=['firls line \n','second line \n','third line\n'] 
with open ('example.txt','a')as file:
    file.writlines(lines)

AttributeError: '_io.TextIOWrapper' object has no attribute 'writlines'

In [ ]:
data=b'\x00\x01\x02\x03\x04'
with open('example.bin','wb') as file:
    file.write(data)

parket orc
.file types used industry

program to count number of characters and numbers in the given data

In [ ]:
def count_text_file(file_path):
    with open (file_path,'r') as file:
        lines=file.readline()
        line_count=len(lines)
        word_count=sum(len(line.split()) for line in lines)
        char_count=sum(len(line) for line in lines)
    return line_count, word_count, char_count

file_path = example.txt
liness,words, character =count_text_file(file_path)
print(f'Lines: {liness}, Words: {words}, characters: {character}')

In [ ]:
with open ('example.txt','w+') as file:
    file.write ("hello world \n")
    file.write("this is a new line \n")

    file.seek(0)

    content =file.read()
    print(content)

In [ ]:
import os 
csd =os.getcwd()
print(f"current working directory is {csd}")

In [ ]:
new_directory="package"
os.mkdir(new_directory)
print(f"Directory '{new_directory }' create")

In [ ]:
item=os.listdir(',')
print(item)

In [ ]:
dir_name ="folder"
file_name="file.txt"
full_path=os.path.join(os.getcwd(),dir_name,file_name)
print(file_path)

In [ ]:
path='example.txt'
if os.path.exists(path):
    print(f"the path '{path}'exists")
else:
    print(f"the path '{path}' doe nto exists")

In [ ]:
import os 
path ='example.txt'
if os.path.isfile(path):
    print(f"The path '{path}'is a file.")
elif os.path.isdir(path):
    print(f"The path '{path}' is a directory.")
else:
    print(f"The path '{path}'is neither a file nor a directory,")

In [ ]:
relative_path='example.txt'
absolute_path=os.path.abspath(relative_path)
print(absolute_path)

# numpy 
### NUMPY
##### NUMPY#

In [ ]:
import numpy as np 
# creat a 1D array 
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

In [ ]:
arr1.reshape(5,1)

In [ ]:
np.ones((3,4),dtype=int)
np.eye(3)

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("nmber of dimenstions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("DAta type:",arr.dtype)

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print("Addition:",arr1+arr2)
print("Subtraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Division:",arr1/arr2)
print(np.sqrt(arr1))

print(np.exp(arr))

print(np.sin(arr))

In [ ]:
ls=[[1,2,3,4],[4,5,6]]
ls[0][1]

In [ ]:
ls=[[1,2,3,4],[4,5,6]]
ls[0][1]
2
ls=[[1,2,3,4],[4,5,6,1]]
ls[0][1]

2
ls[0:1][2:3]
[]
ls[0][2:3]
[3]

ls[0:1]
[[1, 2, 3, 4]]
l=ls[0:1]
l[2:3]
[]

In [ ]:
print("Hello")

:

In [ ]:
Array:[[1 2 3 4]
       [5 6 7 8]
       [9 10 11 12]]
Array[1:]=100
Array

:

In [ ]:
data =np.array([1,2,3,4,5])

mean = np.mean (dat)
st_dev =np.std(data)

normalized_data =(data-mean)/st_dev

:

In [ ]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[data>=5 & (data<=8)]

In [ ]:
print("HELLO")

In [ ]:
from math import sqrt,p1
print(sqrt(16))
print(sqrt(16))
print(p1)

In [ ]:
print("ehllO")

ehllO

CREATE YOUR 9I

In [ ]:
from destination import ADDI as asi
asi.add(10,5)
asi.sub(10,5)

5

In [ ]:
asi.sub(10,5)

5

In [ ]:
asi.multiply(10,5)

50

In [ ]:
asi.divide(10,5)

2.0

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd 
data=[1, 2, 3, 4, 5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data={'Name':['Krish','John','Jack'],
      'Age':[25,30,35],
      'city':['New York','London','Paris']

      }
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      city
0  Krish   25  New York
1   John   30    London
2   Jack   35     Paris
<class 'pandas.DataFrame'>

In [ ]:
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [ ]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('sales_data.csv')
df.head(50)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card
10,10011,2024-01-11,Beauty Products,Chanel No. 5 Perfume,1,129.99,129.99,Europe,PayPal
11,10012,2024-01-12,Sports,Babolat Pure Drive Tennis Racket,3,199.99,599.97,Asia,Credit Card
12,10013,2024-01-13,Electronics,Samsung Galaxy Tab S8,2,749.99,1499.98,North America,Credit Card
13,10014,2024-01-14,Home Appliances,Keurig K-Elite Coffee Maker,1,189.99,189.99,Europe,PayPal
14,10015,2024-01-15,Clothing,North Face Down Jacket,2,249.99,499.98,Asia,Debit Card
15,10016,2024-01-16,Books,"Salt, Fat, Acid, Heat by Samin Nosrat",3,35.99,107.97,North America,Credit Card
16,10017,2024-01-17,Beauty Products,Dyson Supersonic Hair Dryer,1,399.99,399.99,Europe,PayPal
17,10018,2024-01-18,Sports,Manduka PRO Yoga Mat,4,119.99,479.96,Asia,Credit Card
18,10019,2024-01-19,Electronics,Garmin Forerunner 945,2,499.99,999.98,North America,Credit Card
19,10020,2024-01-20,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal
20,10021,2024-01-21,Clothing,Zara Summer Dress,3,59.99,179.97,Asia,Debit Card
21,10022,2024-01-22,Books,Gone Girl by Gillian Flynn,2,22.99,45.98,North America,Credit Card
22,10023,2024-01-23,Beauty Products,Olay Regenerist Face Cream,1,49.99,49.99,Europe,PayPal
23,10024,2024-01-24,Sports,Adidas FIFA World Cup Football,3,29.99,89.97,Asia,Credit Card
24,10025,2024-01-25,Electronics,Bose QuietComfort 35 Headphones,1,299.99,299.99,North America,Credit Card
25,10026,2024-01-26,Home Appliances,Panasonic NN-SN966S Microwave,1,179.99,179.99,Europe,PayPal
26,10027,2024-01-27,Clothing,Adidas Ultraboost Shoes,2,179.99,359.98,Asia,Debit Card
27,10028,2024-01-28,Books,Pride and Prejudice by Jane Austen,3,12.99,38.97,North America,Credit Card
28,10029,2024-01-29,Beauty Products,MAC Ruby Woo Lipstick,1,29.99,29.99,Europe,PayPal
29,10030,2024-01-30,Sports,Nike Air Zoom Pegasus 37,2,129.99,259.98,Asia,Credit Card
30,10031,2024-01-31,Electronics,Sony WH-1000XM4 Headphones,2,349.99,699.98,North America,Credit Card
31,10032,2024-02-01,Home Appliances,Instant Pot Duo,3,89.99,269.97,Europe,PayPal
32,10033,2024-02-02,Clothing,Under Armour HeatGear T-Shirt,5,29.99,149.95,Asia,Debit Card
33,10034,2024-02-03,Books,1984 by George Orwell,4,19.99,79.96,North America,Credit Card
34,10035,2024-02-04,Beauty Products,L'Oreal Revitalift Serum,2,39.99,79.98,Europe,PayPal
35,10036,2024-02-05,Sports,Peloton Bike,1,1895.00,1895.00,Asia,Credit Card
36,10037,2024-02-06,Electronics,Apple Watch Series 8,3,399.99,1199.97,North America,Credit Card
37,10038,2024-02-07,Home Appliances,Roomba i7+,2,799.99,1599.98,Europe,PayPal
38,10039,2024-02-08,Clothing,Columbia Fleece Jacket,4,59.99,239.96,Asia,Debit Card
39,10040,2024-02-09,Books,Harry Potter and the Sorcerer's Stone,3,24.99,74.97,North America,Credit Card
40,10041,2024-02-10,Beauty Products,Estee Lauder Advanced Night Repair,1,105.00,105.00,Europe,PayPal
41,10042,2024-02-11,Sports,Fitbit Charge 5,2,129.99,259.98,Asia,Credit Card
42,10043,2024-02-12,Electronics,GoPro HERO10 Black,3,399.99,1199.97,North America,Credit Card
43,10044,2024-02-13,Home Appliances,Nespresso VertuoPlus,1,199.99,199.99,Europe,PayPal
44,10045,2024-02-14,Clothing,Patagonia Better Sweater,2,139.99,279.98,Asia,Debit Card
45,10046,2024-02-15,Books,Becoming by Michelle Obama,4,32.50,130.00,North America,Credit Card
46,10047,2024-02-16,Beauty Products,Clinique Moisture Surge,1,52.00,52.00,Europe,PayPal
47,10048,2024-02-17,Sports,Yeti Rambler Tumbler,6,39.99,239.94,Asia,Credit Card
48,10049,2024-02-18,Electronics,Kindle Paperwhite,2,129.99,259.98,North America,Credit Card
49,10050,2024-02-19,Home Appliances,Breville Smart Oven,1,299.99,299.99,Europe,PayPal

In [ ]:
df

    Name  Age      city
0  Krish   25  New York
1   John   30    London
2   Jack   35     Paris

In [ ]:
print(df.dtypes)

Name      str
Age     int64
city      str
dtype: object

In [ ]:
df['Product Name']

0                                        iPhone 14 Pro
1                                     Dyson V11 Vacuum
2                                     Levi's 501 Jeans
3                                    The Da Vinci Code
4                              Neutrogena Skincare Set
                            ...
235    Nespresso Vertuo Next Coffee and Espresso Maker
236                          Nike Air Force 1 Sneakers
237             The Handmaid's Tale by Margaret Atwood
238               Sunday Riley Luna Sleeping Night Oil
239                         Yeti Rambler 20 oz Tumbler
Name: Product Name, Length: 240, dtype: str

In [ ]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

loc is used to select rows and columns by label.

You can pass it. Asingle label. A list of label. A slice of labels. A boolean Seires- A colon (which indicates "all labels.")

tHIS IS important for

In [ ]:
df.loc[0:5, ['Product Name', 'Region']]

                  Product Name         Region
0                iPhone 14 Pro  North America
1             Dyson V11 Vacuum         Europe
2             Levi's 501 Jeans           Asia
3            The Da Vinci Code  North America
4      Neutrogena Skincare Set         Europe
5  Wilson Evolution Basketball           Asia

In [ ]:
df.loc[0,:]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [ ]:
df.loc[[0,1,2],:]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [ ]:
df.loc[0:2, ['Product Name','Units Sold']]

       Product Name  Units Sold
0     iPhone 14 Pro           2
1  Dyson V11 Vacuum           1
2  Levi's 501 Jeans           3

In [ ]:
df[['Product Name','Units Sold']].head(3)

       Product Name  Units Sold
0     iPhone 14 Pro           2
1  Dyson V11 Vacuum           1
2  Levi's 501 Jeans           3

iloc is used to select rows and columns by integer poistion. YOu can pass it:
A single integer poisition
A list of integer positions
A slice of integer poistion
A colon ( which indicates "all iteger positions")

In [ ]:
df.iloc[0:2,0:4]

   Transaction ID        Date Product Category      Product Name
0           10001  2024-01-01      Electronics     iPhone 14 Pro
1           10002  2024-01-02  Home Appliances  Dyson V11 Vacuum

In [ ]:
df.iloc[0:2, :]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal

In [ ]:
df[0:2]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal

In [ ]:
df.iloc[0:][2:]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
df.drop('Salary',axis=1,inplace=True)

KeyError: "['Salary'] not found in axis"

In [ ]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean(),inplace=True)

KeyError: 'Age'

In [ ]:
df.drop(0,inplace=True)

The Magic Which you are loop looking for is in the work which you are avoiding

In [ ]:
df=pd

In [ ]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
print("Data types:\n",df.dtypes)
print("Statistical summary:\n",df.describe())

The Magic Which you are looking for is in the work which you are avoiding
The Magic Which You Are looking For Is In The Work Which You Are Avoiding
The Magic Which You Are Looking For Is In The Work Which You Are Avoiding
The Magic Which You Are

In [ ]:
df=pd.read_csv('data.csv')
## fetch the first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

The Magic Which You Are Looking For Is In The Work Which You Are Avoiding 


This is one of the Most important one

In [ ]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df_filled=df.fillna(0)

In [ ]:
df_filled=df.fillna(0)

In [ ]:
df_filled

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df['new']

NameError: name 'df' is not defined

In [ ]:
df.add(df['new'],axis=1)

NameError: name 'df' is not defined

In [ ]:
df_filled.add(df['new'],axis=1)

NameError: name 'df_filled' is not defined

In [ ]:
df=df.reader(columns=('Date':'Sales_Date'))

In [ ]:
df['ac']=0

NameError: name 'df' is not defined

In [ ]:
df['value_new']=df['Value'].astype(int)
df.head()
## this is just for example weather this code works or not because this error producing code

In [ ]:
df['value']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

NameError: name 'df' is not defined

In [ ]:
df['new_Value']=df['Value'].apply(lambda x:x*2)
df.head()

groupby and joints homework self study

In [15]:
import pandas as pd

In [16]:
df=pd.read_csv('sales_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
df.groupby('Product Category')

In [ ]:
group_by_frame=df.groupby('Product Category')

In [ ]:
df.groupby('Product Category')[['Units Sold', 'Total Revenue']].mean()

                  Units Sold  Total Revenue
Product Category
Beauty Products        1.150       65.54750
Books                  2.850       46.54825
Clothing               3.625      203.22325
Electronics            1.650      874.56025
Home Appliances        1.475      466.15400
Sports                 2.200      358.16300

In [18]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [22]:
df['Total Revenue']=df['Unit Price'].apply(lambda x:x*2)

In [23]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,999.98,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,139.98,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,31.98,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,179.98,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,319.98,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,180.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,21.98,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,110.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [31]:
grouped_sum=df.groupby([ 'Region','Product Category'])[['Total Revenue']].mean()

In [32]:
print(grouped_sum)

                                Total Revenue
Region        Product Category
Asia          Clothing                135.073
              Sports                  522.568
Europe        Beauty Products         123.246
              Home Appliances         640.371
North America Books                    32.306
              Electronics            1383.183

In [34]:
grouped_agg=df.groupby('Region')['Units Sold'].agg(['mean','sum','count'])

In [35]:
grouped_agg

                 mean  sum  count
Region
Asia           2.9125  233     80
Europe         1.3125  105     80
North America  2.2500  180     80

In [37]:
df1=pd.DataFrame({'Key':['a','b','c'],'value1':[1,2,3]})
df2=pd.DataFrame({'Key':['a','b','d'],'value2':[1,2,3]})

In [38]:
df2

  Key  value2
0   a       1
1   b       2
2   d       3

In [39]:
df1

  Key  value1
0   a       1
1   b       2
2   c       3

In [45]:
pd.merge(df1,df2,df3, on="Key",how="inner")

TypeError: merge() got multiple values for argument 'how'

In [46]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  value1  value2
0   a     1.0     1.0
1   b     2.0     2.0
2   c     3.0     NaN
3   d     NaN     3.0

In [42]:
pd.merge(df1,df2,on="Key",how="left")

  Key  value1  value2
0   a       1     1.0
1   b       2     2.0
2   c       3     NaN

In [44]:
df3=pd.DataFrame({'Key':['a','b','c'],'value1':[1,2,3]})

## Data time and

In [19]:
df=pd.DataFrame({'date':['3/10/2023','4/10/2023','5/10/2023'],'value':[10,20,30]})

In [21]:
df

        date  value
0  3/10/2023     10
1  4/10/2023     20
2  5/10/2023     30

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      str
 1   value   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      str
 1   value   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [23]:
df['date']=pd.to_datetime(df['date'])

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[us]
 1   value   3 non-null      int64
dtypes: datetime64[us](1), int64(1)
memory usage: 180.0 bytes

In [51]:
df

        date  value
0 2023-03-10     10
1 2023-04-10     20
2 2023-05-10     30

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   DoB     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [53]:
df['date']=pd.to_datetime(df['date'],dayfirst=True)

In [54]:
df

        date  value
0 2023-03-10     10
1 2023-04-10     20
2 2023-05-10     30

In [9]:
df=pd.DataFrame({'date':['2016-a-10 20:30:01','2016-10-11 21:30:01','2013-6-12 22:30:01'],'value':[10,20,30]})
#df['date']=pd.to_datetime(df['date'],format="%Y-%d-%m %H:%M:%S")

In [56]:
df

                 date  value
0 2016-10-06 20:30:01     10
1 2016-11-06 21:30:01     20
2 2013-12-06 22:30:01     30

In [10]:
import pandas as pd
df['date']=pd.to_datetime(df['date'],errors='coerce')
df

C:\Users\Ajith\AppData\Local\Temp\ipykernel_29008\960472895.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date']=pd.to_datetime(df['date'],errors='coerce')

                 date  value
0                 NaT     10
1 2016-10-11 21:30:01     20
2 2013-06-12 22:30:01     30

The Magic Which You Are Looking for Is In The Work Which You Are Avoiding

Assemble a datetime from mutiple colmsn

In [6]:
import pandas as pd

In [12]:
df =pd.DataFrame({'year':[2016,2017,2018],'month':[1,2,3],'day':[10,11,12]})

In [26]:
df['date']=pd.to_datetime(df)

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing

The magic which you are looking for is in the work which you are avoiding

In [9]:
df

   year  month  day       date
0  2016      1   10 2016-01-10
1  2017      2   11 2017-02-11
2  2018      3   12 2018-03-12

In [40]:
df=pd.DataFrame({'name':['Tom','Andy','Lucas'],'DoB':['08-05-1997','03-28-1995','12-16-1995']})

In [15]:
df

    name         DoB
0    Tom  08-05-1997
1   Andy  03-28-1995
2  Lucas  12-16-1995

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   DoB     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [44]:
df['year']=pd.to_datetime(df['DoB'])

In [31]:
df

    name         DoB       year
0    Tom  08-05-1997 1997-08-05
1   Andy  03-28-1995 1995-03-28
2  Lucas  12-16-1995 1995-12-16

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   DoB     3 non-null      str
 2   year    3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [43]:
df['DoB']=pd.to_datetime(df['DoB'])

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   DoB     3 non-null      datetime64[us]
 2   year    3 non-null      datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 204.0 bytes

In [45]:
df['year']=df['DoB'].dt.year
df['month']=df['DoB'].dt.month
df['day']=df['DoB'].dt.day

In [46]:
df

    name        DoB  year  month  day
0    Tom 1997-08-05  1997      8    5
1   Andy 1995-03-28  1995      3   28
2  Lucas 1995-12-16  1995     12   16

Get the week of yea,r the day of week and leap year

In [ ]:
df['day_of_week']=df['DoB'].dt.dayofweek

In [48]:
df['is_leap_year']=df['DoB'].dt.is_leap_year
df

    name        DoB  year  month  day  day_of_week  is_leap_year
0    Tom 1997-08-05  1997      8    5            1         False
1   Andy 1995-03-28  1995      3   28            1         False
2  Lucas 1995-12-16  1995     12   16            5         False

In [49]:
df['DoB'].dt.weekday

0    1
1    1
2    5
Name: DoB, dtype: int32

In [50]:
dw_mapping={
    0: 'Monday',
    1: 'Tuesday',
    2:'Wednesday',
    3:'Thursday',
    4:'Friday',
    5:'Saturday',
    6:'Sunday'
}
df['day_of_week_name']=df['DoB'].dt.weekday.map(dw_mapping)

In [51]:
df['day_of_week_name']

0     Tuesday
1     Tuesday
2    Saturday
Name: day_of_week_name, dtype: str

In [52]:
df

,name,DoB,year,month,day,day_of_week,is_leap_year,day_of_week_name
0,Tom,1997-08-05,1997,8,5,1,False,Tuesday
1,Andy,1995-03-28,1995,3,28,1,False,Tuesday
2,Lucas,1995-12-16,1995,12,16,5,False,Saturday

In [65]:
today=pd.to_datetime('today')
df['age']=today.year - df['DoB'].dt.year

In [66]:
df

,name,DoB,year,month,day,day_of_week,is_leap_year,day_of_week_name,age
0,Tom,1997-08-05,1997,8,5,1,False,Tuesday,29
1,Andy,1995-03-28,1995,3,28,1,False,Tuesday,31
2,Lucas,1995-12-16,1995,12,16,5,False,Saturday,31

In [67]:
diff_y =today.year -df['DoB'].dt.year
b_md=df['DoB'].apply(lambda x: (x.month,x.day))
no_birthday = b_md > (today.month,today.day)
df['age']=diff_y- no_birthday

In [68]:
df

,name,DoB,year,month,day,day_of_week,is_leap_year,day_of_week_name,age
0,Tom,1997-08-05,1997,8,5,1,False,Tuesday,29
1,Andy,1995-03-28,1995,3,28,1,False,Tuesday,31
2,Lucas,1995-12-16,1995,12,16,5,False,Saturday,30